### ISSUE TITLE
Macos readme?

### ISSUE THREAD

**Issue by starkoracles** [mercush/risc0_profiling_tool#1]
Hi! I'm new to the ecosystem and I'm not sure if riscv64-unknown-elf-objdump is runnable on macos and how to run it?

**Comment by mercush** [comment]
> Hi! I'm new to the ecosystem and I'm not sure if riscv64-unknown-elf-objdump is runnable on macos and how to run it?

Hey! Thanks for checking out my code. Unfortunately, you'll have to get an Ubuntu VM for this to work. This is also convenient if you want to use more sophisticated profiling tools like gprof and perf. I don't think macos supports either. 
Lmk if you want to help out though. I was planning on making this a TUI kind of like perf and gprof.

**Comment by starkoracles** [comment]
Thanks for your answer! I reached out on discord, would love to chat!

**Comment by starkoracles** [comment]
I was able to use brew binutils to disassemble the file
